---
# Use version 2 since version 3 does not support very rich network
# configuration
version: "2.4"

services:
  exim4:
    image: dairiki/exim4-relay:${TAG:-dev}
    build:
      context: .
      labels:
        org.label-schema.version: ${VERSION}
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.vcs-ref: ${VCS_REF}
    environment:
      ETC_MAILNAME: smtp.dairiki.org
      dc_readhost: dairiki.org
      dc_smarthost: "smtp.pobox.com::587"
      GLOBAL_RCPT_RATELIMIT: "100/1h"
      TZ: "${TZ:-America/Los_Angeles}"
      HUBBED_HOSTS: |
        # Mail to dairiki.org can be delivered directly to MX (The
        # rest has to go trough MSA, which is rate limited.)
        # However, we can't seem to make outgoing connections to SMTP
        # port 25 from home.  So route these to our external MSA.
        #dairiki.org: dairiki.org/MX bydns
        dairiki.org: zabbix.dairiki.org::587
    ports:
      - "127.0.0.1:25:25"
